### PR TITLE
Update mara logo for 2024 (marketing approved)

### PR DESCRIPTION
**Pull request by hunicus**
Got the logo for #23 from a contact at Mara.

Marketing intervened after it was merged and specified that the light mode version should be used instead.

Screenshot from 2024-08-19 12-33-10

### CODE REVIEW

**Comment by nymkappa** [comment]
You don't have access to this repo?

**Comment by hunicus** [comment]
No, I tried pushing a branch to this repo and couldn't so I forked.

**Review by wiz — CHANGES_REQUESTED** [review]
NACK

**Comment by hunicus** [comment]
Why?

**Pull request closed without merging**
