### PR TITLE
Create braiinspool.svg

### PR DESCRIPTION
**Pull request by bitcoinminion**
Proposal for the Braiins Pool logo

### CODE REVIEW

**Comment by nymkappa** [comment]
That logo does not look good to fill a small square, do you have an alternative similar to previous "SP" (SlushPool) logo?

Screenshot 2022-11-09 at 6 36 48 AM
Screenshot 2022-11-09 at 6 37 53 AM

**Comment by bitcoinminion** [comment]
braiins_logo

**Review by nymkappa — CHANGES_REQUESTED** [review]
The image does not render properly, maybe a transparency issue? Make sure to fill up the letter shape with white

image

Please use commit for updating your PR content as well 👍🏻

**Comment by bitcoinminion** [comment]
braiins_logo

**Comment by bitcoinminion** [comment]
Done

**Review by nymkappa — APPROVED** [review]

**Comment by bitcoinminion** [comment]
Do you know when the changes will be reflected?

Regards

**Pull request merged**
